services:
  app:
    container_name: app
    build:
      context: .		
      dockerfile: Dockerfile
    volumes:		
      - type: bind
        source: ./app
        target: /workspaces
    #"react-sample"の部分はプロジェクト名
    command: sh -c "cd next-sample && npm run dev"
    ports:
      - 3000:3000	
    stdin_open: true #標準入力をコンテナと紐付ける
